spring:
  r2dbc:
    username: {DATABASE_USERNAME}
    password: {DATABASE_PASSWORD}
    url: r2dbc:postgresql://localhost:{DATABASE_PORT}/postgres
  flyway:
    url: jdbc:postgresql://localhost:{DATABASE_PORT}/postgres
    locations: classpath:db/postgres/migration
  webflux:
    base-path: /api/v1
  security:
    user:
      roles: manager
      name: {USER_NAME}
      password: {USER_PASSWORD}