database.port: ${DATABASE_PORT}

spring:
  r2dbc:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: r2dbc:postgresql://localhost:${database.port}/postgres
  flyway:
    url: jdbc:postgresql://localhost:${database.port}/postgres
    locations: classpath:db/postgres/migration
  webflux:
    base-path: /api/v1
  security:
    user:
      roles: { USER_ROLE }
      name: {USER_NAME}
      password: {USER_PASSWORD}

springdoc:
  swagger-ui:
    enabled: true
#    path: reactive/swagger-ui.html
#  api-docs:
#    path: /reactive-docs

server:
  port: { APPLICATION_PORT }